code --install-extension Sophisticode.php-formatter
code --install-extension austenc.laravel-blade-spacer
code --install-extension bceskavich.theme-dracula-at-night
code --install-extension be5invis.vscode-custom-css
code --install-extension bernardodsanderson.theme-material-neutral
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension christian-kohler.npm-intellisense
code --install-extension cjhowe7.laravel-blade
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension febean.vue-format
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension file-icons.file-icons
code --install-extension fisheva.eva-theme
code --install-extension fivepointseven.vscode-theme-onedark-vivid
code --install-extension flydreame.docblocker
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Dark-Dracula
code --install-extension HaiUIT.onedark-operator-custom
code --install-extension hollowtree.vue-snippets
code --install-extension HookyQR.beautify
code --install-extension HvyIndustries.crane
code --install-extension kkozee.theme-one-dark-vivid
code --install-extension kokororin.vscode-phpfmt
code --install-extension mariorodeghiero.vue-theme
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-attrs-sorter
code --install-extension ms-vscode.sublime-keybindings
code --install-extension neilbrayfield.php-docblocker
code --install-extension octref.vetur
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel5-snippets
code --install-extension PKief.material-icon-theme
code --install-extension predrag-nikolic.php-class-helper
code --install-extension presidentma.axios-snippets
code --install-extension rifi2k.format-html-in-php
code --install-extension robertohuertasm.vscode-icons
code --install-extension ryannaddy.laravel-artisan
code --install-extension sachittandukar.laravel-5-snippets
code --install-extension shekhardtu.vuejspack
code --install-extension sianglim.slim
code --install-extension sldobri.fantastical-php-code
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension WallabyJs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension whizkydee.material-palenight-theme
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Zaczero.bootstrap-v4-snippets
code --install-extension zhuangtongfa.Material-theme
